version: '3.3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    ports:
      - 80:80
    environment:
      PHP_ENABLE_XDEBUG: 1
    volumes:
      - ./:/app
    links:
      - pgsql

  pgsql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yii2test
      - POSTGRES_USER=yii2test
      - POSTGRES_PASSWORD=yii2test

volumes:
  pgdata:
    driver: local
